name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pylint bandit

      - name: Run tests
        run: pytest tests/unit/ -v

      - name: Run linting
        run: pylint src/calculator.py

      - name: Run security scan
        run: |
    bandit -r src --skip B101,B110 --severity-level medium || true
