name: CI Pipeline

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest pytest-cov pylint black bandit click

      # 4️⃣ Run all tests (unit + integration) with coverage
      - name: Run tests and generate coverage
        run: |
          pytest tests/ --cov=src --cov-report=term-missing --cov-report=html

      # 5️⃣ Upload coverage HTML report
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov/

      # 6️⃣ Run lint (pylint)
      - name: Lint source
        run: |
          pylint src/ || true

      # 7️⃣ Check formatting (black)
      - name: Check formatting
        run: |
          black src/ tests/ --check || (black src/ tests/ && echo "Auto-formatted code")

      # 8️⃣ Security scan (bandit)
      - name: Run security scan
        run: |
          bandit -r src/ -v || true

      # 9️⃣ Package optional build artifact
      - name: Package artifact
        run: |
          zip -r build_artifact.zip src tests htmlcov
        continue-on-error: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_artifact
          path: build_artifact.zip
